### ISSUE TITLE
New VRT icons available

### ISSUE THREAD

**Issue by klump** [cryptofuture/vrt-sheet-for-dia#1]
Hi there!

I have noticed that there are new awesome VRT icons available (version 1.2.0). Can you update the icons or describe how you have converted the icons?

http://www.vrt.com.au/downloads/vrt-network-equipment

**Comment by cryptofuture** [comment]
I'm aware about new icons. Main problem VRT changed some icons categories and names and images. And that means mostly all icons should be converted from beginning to be the same as new version. If I remember right first you need to open every icons in Draw, then paste it to Inkscape and then convert exported svg to xml and png with Image2Dia.

**Comment by klump** [comment]
I have converted the icons to svg with OpenOffice 4.1.2. You maybe want to check them out in my new branch and do some quality assurance before we merge... However, I have not done any work towards dia, I am quite content with SVG only.

https://github.com/klump/vrt-sheet-for-dia/tree/new-svg

**Comment by cryptofuture** [comment]
Just pushed update to 1.2.0 VRT extension.
